export default {
  getHomeData:{
    method:'get',
    url:'/mock/homeData.json'
  },
  getNavData:{
    method:'get',
    url:'/mock/navData.json'
  },
  
  getUserData:{
    method:'get',
    url:'/mock/userData.json'
  },
  getUserList:{
    method:'get',
    url:'/mock/userList.json'
  },
  getSearchTableData:{
    method:'get',
    url:'/mock/searchTableData.json'
  },
  getOptionNData:{
    method:'get',
    url:'/mock/optionData.json'
  },
  saveTabelData:{
    method:'get',
    url:'/mock/success.json'
  },
  getListData:{
    method:'get',
    url:'/mock/listData.json'
  },
  getDetailData:{
    method:'get',
    url:'/mock/detailData.json'
  },

  getUserListM:{
    method:'get',
    url:'/mock/user-list.json'
  },
  getTabTable:{
    method:'get',
    url:'/mock/tab-table.json'
  },

  getGoodsList:{
    method:'get',
    url:'/api/good'
  },

  // 故事相关
  getStoryList:{
    method:'get',
    url:'/api/story/list'
  },
  getStoryDetail:{
    method:'get',
    url:'/api/story/detail'
  },
  doStoryAddRemark:{
    method:'post',
    url:'/api/story/add-remark'
  },
  doStoryRemoveRemark:{
    method:'post',
    url:'/api/story/remove-remark'
  },
  doStoryAddWatch:{
    method:'post',
    url:'/api/story/add-watch'
  },

  //评论相关
  getRemarkList:{
    method:'get',
    url:'/api/remark/list'
  },
  addRemark:{
    method:'post',
    url:'/api/remark/add'
  },
  removeRemark:{
    method:'post',
    url:'/api/remark/remove'
  },
  supportOrAgainstRemark:{
    method:'post',
    url:'/api/remark/support-or-against'
  },

  // 用户相关
  doUserAddRemark:{
    method:'post',
    url:'/api/user/add-remark'
  },
  doUserRemoveRemark:{
    method:'post',
    url:'/api/user/remove-remark'
  },
  userLogin:{
    method:'post',
    url:'/api/user/login'
  },
  userRegister:{
    method:'post',
    url:'/api/user/register'
  },
  getUserBaseInfor:{
    method:'get',
    url:'/api/user/base-infor'
  },
  updateUserInfor:{
    method:'post',
    url:'/api/user/update-infor'
  },
  putCorn:{
    method:'post',
    url:'/api/user/put-corn'
  },
  payCorn:{
    method:'post',
    url:'/api/user/pay-corn'
  },
  addIntoShoppingCar:{
    method:'post',
    url:'/api/user/add-into-shoppingcar'
  },
  removeFromShoppingCar:{
    method:'post',
    url:'/api/user/remove-from-shoppingcar'
  },

}
